on:
  schedule:
  - cron: "0 0 * * 0"
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  run-polycrystal:
    name: Run Polycrystal
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64]
        edition: [flagship, gnome, plasma, xfce]
        releasever: [42]
    container:
      image: ghcr.io/terrapkg/builder:f${{ matrix.releasever }}
      options: --cap-add=SYS_ADMIN --privileged
    steps:
    - name: Install required packages
      run: |
        dnf5 install -y --allowerasing --nogpgcheck \
          --repofrompath 'ultramarine,https://repos.fyralabs.com/um$releasever' \
          polycrystal ultramarine-release-identity-${{ matrix.edition }} ultramarine-repos-extras
    - uses: actions/cache@v4
      with:
        key: flatpak-um${{ matrix.releasever }}-${{ matrix.edition }}-${{ matrix.arch }}
        path: |
          /var/lib/polycrystal
          /var/lib/flatpak
    - run: polycrystal
    - name: Compress to tarball
      run: cd /var/lib && tar -I 'zstd --ultra -22 --long -T0' -cvf /flatpak.tar.zst flatpak/
    - uses: actions/upload-artifact@v4
      with:
        name: flatpak-um${{ matrix.releasever }}-${{ matrix.edition }}-${{ matrix.arch }}
        path: /flatpak.tar.zst
        compression-level: 0

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [run-polycrystal]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Tidy up artifacts
        id: tidy
        run: |
          echo "datetime=$(TZ=utc date +'%Y.%M.%d.%Hh%Mm')" >> "$GITHUB_OUTPUT"
          # also tidy up files
          for f in artifacts/*/flatpak.tar.zst; do
            mv $f $(echo $f | sed 's@/flatpak.tar.zst@.tar.zst@')
            rmdir $(echo $f | sed 's@/flatpak.tar.zst@@')
          done

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          tag_name: ${{ steps.tidy.outputs.datetime }}
          files: artifacts/flatpak-um*.tar.zst

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.SSH_AUTHENTICATION_KEY }}

      - name: Commit and push
        run: |
          mkdir -p ${{ runner.temp }}
          echo "${{ secrets.SSH_SIGNING_KEY }}" > ${{ runner.temp }}/signing_key
          chmod 0700 ${{ runner.temp }}/signing_key
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          echo "${{ steps.tidy.outputs.datetime }}" > latest
          git add latest
          git config user.name "Raboneko"
          git config user.email "raboneko@fyralabs.com"
          git config gpg.format "ssh"
          git config user.signingkey "${{ runner.temp }}/signing_key"
          git commit -S -m "Update `latest`"
          git push -u origin main
          
